// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	RemoteMessage
	Response
*/
package service

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RemoteMessage struct {
	MethodName string `protobuf:"bytes,1,opt,name=MethodName,json=methodName,proto3" json:"MethodName,omitempty"`
	Data       []byte `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	Type       int32  `protobuf:"varint,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
}

func (m *RemoteMessage) Reset()                    { *m = RemoteMessage{} }
func (m *RemoteMessage) String() string            { return proto.CompactTextString(m) }
func (*RemoteMessage) ProtoMessage()               {}
func (*RemoteMessage) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0} }

func (m *RemoteMessage) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *RemoteMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RemoteMessage) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Response struct {
	Error string `protobuf:"bytes,1,opt,name=Error,json=error,proto3" json:"Error,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{1} }

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RemoteMessage)(nil), "service.RemoteMessage")
	proto.RegisterType((*Response)(nil), "service.Response")
}

func init() { proto.RegisterFile("message.proto", fileDescriptorMessage) }

var fileDescriptorMessage = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0x55, 0x0a, 0xe7, 0xe2, 0x0d, 0x4a, 0xcd, 0xcd, 0x2f, 0x49, 0xf5, 0x85, 0xc8, 0x0b,
	0xc9, 0x71, 0x71, 0xf9, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0xf8, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x71, 0xe5, 0xc2, 0x45, 0x84, 0x84, 0xb8, 0x58, 0x5c, 0x12, 0x4b, 0x12,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x41, 0x62, 0x21, 0x95,
	0x05, 0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x4a, 0x26,
	0x5c, 0x1c, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x22, 0x5c, 0xac, 0xae, 0x45,
	0x45, 0xf9, 0x45, 0x50, 0xe3, 0x58, 0x53, 0x41, 0x1c, 0x6c, 0x26, 0x25, 0xb1, 0x81, 0x9d, 0x67,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xda, 0x8a, 0x16, 0xaf, 0x00, 0x00, 0x00,
}
